// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfEljN9h0kpFN6O70lH0ll_DXk0gkQIcY',
    appId: '1:229228143984:web:e8df13cad21815093c9bb5',
    messagingSenderId: '229228143984',
    projectId: 'roomie-roast-akash-2026',
    authDomain: 'roomie-roast-akash-2026.firebaseapp.com',
    storageBucket: 'roomie-roast-akash-2026.firebasestorage.app',
    measurementId: 'G-H3BQHJPK4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQuijIw5FrjziJkfU472DZOR62LIUjHMU',
    appId: '1:229228143984:android:fa94822aae7147ff3c9bb5',
    messagingSenderId: '229228143984',
    projectId: 'roomie-roast-akash-2026',
    storageBucket: 'roomie-roast-akash-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx108ZfmKdhsJjQQA3oD8RYdHYVVgi-GI',
    appId: '1:229228143984:ios:93b3c43dda4521573c9bb5',
    messagingSenderId: '229228143984',
    projectId: 'roomie-roast-akash-2026',
    storageBucket: 'roomie-roast-akash-2026.firebasestorage.app',
    iosBundleId: 'com.example.roomieRoast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx108ZfmKdhsJjQQA3oD8RYdHYVVgi-GI',
    appId: '1:229228143984:ios:93b3c43dda4521573c9bb5',
    messagingSenderId: '229228143984',
    projectId: 'roomie-roast-akash-2026',
    storageBucket: 'roomie-roast-akash-2026.firebasestorage.app',
    iosBundleId: 'com.example.roomieRoast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfEljN9h0kpFN6O70lH0ll_DXk0gkQIcY',
    appId: '1:229228143984:web:9547d6ca98c9ffe23c9bb5',
    messagingSenderId: '229228143984',
    projectId: 'roomie-roast-akash-2026',
    authDomain: 'roomie-roast-akash-2026.firebaseapp.com',
    storageBucket: 'roomie-roast-akash-2026.firebasestorage.app',
    measurementId: 'G-RL7M25RT2Y',
  );
}
